"""add uri, country and date columns to photo table

Revision ID: 2053ac39fcb5
Revises: b924c9fae80b
Create Date: 2026-03-13 19:58:59.754434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2053ac39fcb5'
down_revision = 'b924c9fae80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uri', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('country', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('country')
        batch_op.drop_column('uri')

    # ### end Alembic commands ###
